services:
  database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME:-username}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-password}
      - POSTGRES_DB=${DATABASE_NAME:-database}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
